import { api, toErrorMessage } from './api';

export type ExportFormat = 'csv' | 'xlsx' | 'pdf';

const MIME: Record<ExportFormat, string> = {
  csv: 'text/csv;charset=utf-8',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pdf: 'application/pdf',
};

export interface ExportParams {
  range?: string;
  from?: string;
  to?: string;
  groupBy?: string;
}

/**
 * Downloads a real report file generated by the backend from live database
 * data. The request is authenticated, so no token is ever put in a URL.
 */
export async function downloadReport(
  type: string,
  format: ExportFormat,
  params: ExportParams,
  openInNewTab = false,
): Promise<void> {
  const res = await api.get(`/reports/${type}/export`, {
    params: { ...params, format },
    responseType: 'blob',
  });

  const blob = new Blob([res.data as BlobPart], { type: MIME[format] });
  const objectUrl = URL.createObjectURL(blob);

  if (format === 'pdf' && openInNewTab) {
    window.open(objectUrl, '_blank', 'noopener,noreferrer');
    setTimeout(() => URL.revokeObjectURL(objectUrl), 60_000);
    return;
  }

  const link = document.createElement('a');
  link.href = objectUrl;

  // Prefer the server supplied filename when present
  const disposition = res.headers?.['content-disposition'] as string | undefined;
  const match = disposition?.match(/filename="?([^"]+)"?/);
  const stamp = new Date().toISOString().slice(0, 10);
  link.download = match?.[1] ?? `BK-${type}-report-${stamp}.${format}`;

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(objectUrl), 5_000);
}

export function exportErrorMessage(error: unknown): string {
  return toErrorMessage(error, 'Export failed. Please try again.');
}
